version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
