# title: Lurk Rustfmt Configuration
# author: John C. Burnham <john@yatima.io>

# For additional information about Rustfmt options see:
# https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=

# General
edition                      = "2021"     # Rust edition
newline_style                = "Unix"     # never allow Windows' \n\r newlines

# Indent
hard_tabs                    = false      # hard tabs break consistent layout
tab_spaces                   = 2          # override default 4 space indent

# Imports
reorder_imports              = true       # reorder from source

# Width
max_width                    = 80         # don't go over 80 columns
use_small_heuristics         = "Max"      # inherit max width for most objects

# Layout
fn_args_layout               = "Tall"     # single line if short, else vertical 
force_explicit_abi           = true       # C doesn't deserve to be special

# Reordering
reorder_modules             = true        # reorder alphabetically in group

# Punctuation
remove_nested_parens        = true        # ((foo)) => (foo)

# Match blocks
match_arm_leading_pipes     = "Never"     # no leading | in match arms
match_block_trailing_comma  = true        # put a , after a { } match block

# Attributes 
merge_derives               = true        # merge trait derives to one line

# Shorthand
use_field_init_shorthand    = true        # replace Foo { x: x } with Foo { x }
use_try_shorthand           = true        # replace try! with ?
