# Creates a PR benchmark comment with a comparison to main
name: Benchmark pull requests
on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Comparative PR benchmark comment
    if:
      github.event.issue.pull_request
      && github.event.issue.state == 'open'
      && (contains(github.event.comment.body, '!benchmark') || contains(github.event.comment.body, '!gpu-benchmark'))
      && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    uses: lurk-lab/ci-workflows/.github/workflows/bench-pr-comment.yml@main
    with:
      default-runner: "self-hosted,gpu-bench"
      default-benches: "fibonacci"
      default-env: "LURK_BENCH_OUTPUT=pr-comment LURK_RC=100,600"
