name: Generate and deploy crate docs

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  docs:
    uses: lurk-lab/ci-workflows/.github/workflows/docs.yml@main